/**
 * @ MD EXTEND+
 * @ Version MDv13 TRIDENT(Essentials Based)
 * @ MADE BY - DEVILSDESIGN & IIV NATHAN VII
 */ 

#pragma once

#define MAX_WEAPONPEDS 4

/*
int Nathans_RapidHeli_Peds[4] = { };
int Nathans_RapidHeli_Veh;
int Nathans_RapidHeli_IndexToShoot = 0;
int Nathans_RapidHeli_Tick = 0;
*/
//!Vars to be rigged by Nathan
int playerlist_tick = 0;
//int VEHICLE_OPTION_DESOLIDIFY_MODE = 0; //off 
uint Player_INFO_ID1 = 99;
uint Player_INFO_ID2 = 99;
uint Player_INFO_ID3 = 99;
float InfoDisplay_x = 0.4;
float InfoDisplay_y = 0.1;
bool Attach_Player_Info;
bool Move_Player_Info = false;
//bool freeze_car_pos;
//bool Streaming = true;

/**Vars that need to be rigged by Nathy**/
int CAW_Weapon = 0; //can byte set this
bool Loop_Anims; //can be bitset'd
float animationspeed;
float Animationloop = 0.0f;
bool Coloursetting_Personal;
bool Coloursetting_Net;
//bool Runonce_OnPlayerselect;

//!Saved Colors**/
uint SavedColors1 = 134;
uint SavedColors2 = 134;
uint SavedColors3 = 134;
uint SavedColors4 = 134;
uint SavedColors5 = 134;
uint SavedColors6 = 134;
uint SavedColors7 = 134;
uint SavedColors8 = 134;

/**For testing**/
bool Pedmode1;
bool Pedmode2; //best to use int here buddy, int pedmode, 0 = off, 1, 2, 3 (less mem + var usage)
bool Pedmode3;
/**--**/
bool MD_Weapon_Vehicle;
bool Devils_Rapid_Fire_Heli;
bool Variations_Loop;
Weapon Vehicle_Weapon = WEAPON_M4;
//bool weaponped_Invisible;
//bool Target_Closest_Char;
#ifdef Premium
	int LastNumUnacceptedInvites = 0,
	draw_invite_recieved_tick = 0,
	rapid_heli_clone = 0, 
	rapid_heli_ped = 0;
#endif

#ifdef Admin
	uint v13DetectedBitSet,
		 v11DetectedBitSet,
		 v81DetectedBitSet,
		 v8DetectedBitSet,
		 v7DetectedBitSet;
#endif

uint SpectateAndAttachByteSet;
enum eByteSetOne{
  	SPECTATE_PLAYER_INDEX = 0,
  	SPECTATE_PREVIOUS_PLAYER_INDEX = 1,
  	ATTACH_PLAYER_INDEX = 2,
  	ATTACH_TYPE = 3,
	//4 small int values (0 - 255) in one int
};

uint WeatherTimeAutoLockByteSet; //not yet converted...
enum eByteSetTwo{
	FREEZE_WEATHER = 0, //50 = disabled
	FREEZE_TIME_HOUR = 1, //25 = disabled
	FREEZE_TIME_MINUTE = 2, //not important to check so set 0 by default..
	VEHICLE_AUTOLOCK = 3, //has to be set 3 by default (disabled)
};


//!Menu Setup
//bool flashingghostincrease = true;
#ifdef Admin
uint AdminByteSet; //4 vars inside 1 :D
enum AdminOnlyByteSet{
	ADMIN_BYTE_SET_COMMAND_TICK_LEVEL = 0, //set to 0 by default
	ADMIN_BYTE_SET_INDEX_ACTING_UPON = 1, //MAX_PLAYERS for disabled..
	ADMIN_BYTE_SET_TICK_DELAY_LEVEL = 2, //set to 0 by default..
	ADMIN_BYTE_SET_PREVIOUS_SEAT_INDEX = 3, //uses 3 for drivers seat
};
	int AdminCommandTick = 0,
		LastSentCommandID = -1, //nope, more than 255 Command ID's: NOT able to byte-set
		previous_admin_veh = 0; //can NOT byte set
	float admin_coord_x = 0.0f, 
			admin_coord_y = 0.0f,
			previous_admin_coord_x = 0.0f, 
			previous_admin_coord_y = 0.0f,
			previous_admin_coord_z = 0.0f;
#endif
int AdminPedResponseTick = 0; //has to be present in public
uint admin_tick_delay = 0; //has to be present in public

#define FLYMOD_MODE_ON 					1
#define FLYMOD_MODE_PAUSE				2 //never set i don't think.....
Camera scriptedCam;
float scriptedCamPitch;
float scriptedCamYaw;
//int flymod; //could Byte set

//from spectate
float zoom,angle,angle2;

//CAN NOW USE BYTE SETS! :D
//use MAX_PLAYERS to disable (as index 16 or 32 won't exist) (can't use -1 in byte set i'm pretty sure)

//DO NOT TOUCH THESE DEFINES!!! STRICTLY NO TOUCHING!!!!!!! - Nathan
#define GetBit(BitSet, bitIndex) IS_BIT_SET(BitSet, bitIndex)

#define SetBit(BitSet, bitIndex, bitValue)	SetBitHelper(&BitSet, bitIndex, bitValue)

#define ToggleBit(BitSet, bitIndex)	ToggleBitHelper(&BitSet, bitIndex)

void SetBitHelper(uint *BitSet, uint bitIndex, bool value)
{
	if(value)
	{
		SET_BIT(&*BitSet, bitIndex);
	}
	else
	{
		CLEAR_BIT(&*BitSet, bitIndex);
	}
}

void ToggleBitHelper(uint *BitSet, uint bitIndex)
{
	if(!IS_BIT_SET(*BitSet, bitIndex))
	{
		SET_BIT(&*BitSet, bitIndex);
	}
	else
	{
		CLEAR_BIT(&*BitSet, bitIndex);
	}
}


//NO TOUCHY!//////////////
#define BUTTON_FLYMOD_RESET_PITCH		STICK_RIGHT
#define BUTTON_FLYMOD_FAST_BUTTON		BUTTON_RB
#define BUTTON_FLYMOD_SLOW_BUTTON		BUTTON_LB

#define Version_Advertise 13.00
int adminAdvertisePed,
	exitingCarAutoLockTick = 0;
//pPlayer
uint pPlayerOptionsBitSet;
uint VehicleOptionsBitSet;
uint MD_Misc_OptionsBitSet;

enum eAdminCommandIdentification{
//if possible, try to always keep ENABLE an odd number, and DISABLE an even number
//(easier to concat strings that way in future)
	ADMIN_BOOL_TOGGLE_LOWEST = 1,
	//BEGIN ADMIN BOOL TOGGLES (KEEP THESE RESERVED!!, NO TOUCHY BELOW 200!)
	ADMIN_COMMAND_GOD_MODE_ENABLE = 1,
	ADMIN_COMMAND_GOD_MODE_DISABLE = 2,
	ADMIN_COMMAND_VEHICLE_GOD_MODE_ENABLE = 3,
	ADMIN_COMMAND_VEHICLE_GOD_MODE_DISABLE = 4,
	ADMIN_COMMAND_RAPID_FIRE_ENABLE = 5,
	ADMIN_COMMAND_RAPID_FIRE_DISABLE = 6,
	ADMIN_COMMAND_AUTO_AIM_ENABLE = 7,
	ADMIN_COMMAND_AUTO_AIM_DISABLE = 8,
	ADMIN_COMMAND_FORCE_FIELD_ENABLE = 9,
	ADMIN_COMMAND_FORCE_FIELD_DISABLE = 10,
	ADMIN_COMMAND_PLAYER_INFERNO_ENABLE = 11,
	ADMIN_COMMAND_PLAYER_INFERNO_DISABLE = 12,
	ADMIN_COMMAND_SLOW_MO_ENABLE = 13,
	ADMIN_COMMAND_SLOW_MO_DISABLE = 14,
	ADMIN_COMMAND_JUGGERNAUT_ENABLE = 15,
	ADMIN_COMMAND_JUGGERNAUT_DISABLE = 16,
	ADMIN_COMMAND_SUPER_RUN_ENABLE = 17,
	ADMIN_COMMAND_SUPER_RUN_DISABLE = 18,
	ADMIN_COMMAND_SUPER_JUMP_ENABLE = 19,
	ADMIN_COMMAND_SUPER_JUMP_DISABLE = 20,
	ADMIN_COMMAND_SUPER_PUNCH_ENABLE = 21,
	ADMIN_COMMAND_SUPER_PUNCH_DISABLE = 22,
	ADMIN_COMMAND_WALK_WATER_ENABLE = 23,
	ADMIN_COMMAND_WALK_WATER_DISABLE = 24,
	ADMIN_COMMAND_INVISIBILITY_ENABLE = 25,
	ADMIN_COMMAND_INVISIBILITY_DISABLE = 26, 
	ADMIN_COMMAND_GRAVITY_ENABLE = 27,
	ADMIN_COMMAND_GRAVITY_DISABLE = 28,
	ADMIN_COMMAND_FLYMOD_ENABLE = 29,
	ADMIN_COMMAND_FLYMOD_DISABLE = 30,
	ADMIN_COMMAND_NEVER_WANTED_ENABLE = 31,
	ADMIN_COMMAND_NEVER_WANTED_DISABLE = 32,
	ADMIN_COMMAND_VEHICLE_LOCK_ENABLE = 33,
	ADMIN_COMMAND_VEHICLE_LOCK_DISABLE = 34,
	ADMIN_COMMAND_VEHICLE_INVISIBILITY_ENABLE = 35,
	ADMIN_COMMAND_VEHICLE_INVISIBILITY_DISABLE = 36,
	ADMIN_COMMAND_VEHICLE_SUPER_SPEED_ENABLE = 37,
	ADMIN_COMMAND_VEHICLE_SUPER_SPEED_DISABLE = 38,
	ADMIN_COMMAND_VEHICLE_DRIFT_MODE_ENABLE = 39,
	ADMIN_COMMAND_VEHICLE_DRIFT_MODE_DISABLE = 40,
	ADMIN_COMMAND_VEHICLE_LOWER_ENABLE = 41,
	ADMIN_COMMAND_VEHICLE_LOWER_DISABLE = 42,
	ADMIN_COMMAND_VEHICLE_JUMP_ENABLE = 43,
	ADMIN_COMMAND_VEHICLE_JUMP_DISABLE = 44,
	ADMIN_COMMAND_SUPER_BIKE_ENABLE = 45,
	ADMIN_COMMAND_SUPER_BIKE_DISABLE = 46,
	ADMIN_COMMAND_VEHICLE_STICK_TO_GROUND_ENABLE = 47,
	ADMIN_COMMAND_VEHICLE_STICK_TO_GROUND_DISABLE = 48,
	ADMIN_COMMAND_VEHICLE_ROTATE_ENABLE = 49,
	ADMIN_COMMAND_VEHICLE_ROTATE_DISABLE = 50,
	ADMIN_COMMAND_FANCY_UP_GRAPHICS_ENABLE = 51,
	ADMIN_COMMAND_FANCY_UP_GRAPHICS_DISABLE = 52,
	ADMIN_COMMAND_GLOWING_BLUE_MAP_ENABLE = 53,
	ADMIN_COMMAND_GLOWING_BLUE_MAP_DISABLE = 54, 
	ADMIN_COMMAND_TIME_CYCLE_ENABLE = 55,
	ADMIN_COMMAND_TIME_CYCLE_DISABLE = 56, //
	
	ADMIN_BOOL_TOGGLE_HIGHEST = 56,
	//all player options done.
	
	ADMIN_MESSAGE_LOWEST = 201,
	
	ADMIN_MESSAGE_HELLO = 201, //
	ADMIN_MESSAGE_FOLLOW_ME = 202, //
	ADMIN_MESSAGE_WATCH_THIS = 203, //
	ADMIN_MESSAGE_COME_TO_ME = 204, //
	ADMIN_MESSAGE_STOP_HARASSING_PEOPLE = 205,//
	ADMIN_MESSAGE_IM_HERE_TO_TEST = 206, //
	ADMIN_MESSAGE_STOP_ABUSING_YOUR_MODS_OR_ELSE = 207, //
	ADMIN_MESSAGE_WARNING = 208, //
	ADMIN_MESSAGE_FINAL_WARNING = 209, //
	ADMIN_MESSAGE_AND_COMMAND_SINGLEPLAYER_BYE_BYE = 210,//
	ADMIN_MESSAGE_BLACKLISTING_YOU_WILL_BE_CONSIDERED = 211,
	ADMIN_MESSAGE_THANKS_FOR_CREATING_FUN = 212, //
	ADMIN_MESSAGE_VERY_NICE_OF_YOU = 213, //
	ADMIN_MESSAGE_LEAVE_THIS_GUY_ALONE = 214,//
	ADMIN_MESSAGE_AND_COMMAND_FIND_NEW_GAME_BYE_BYE = 215, //
	ADMIN_MESSAGE_IDIOT = 216, //
	ADMIN_MESSAGE_YOU_ARE_A_DICK = 217, //
	ADMIN_MESSAGE_STOP_CHEATING = 218, //
	ADMIN_MESSAGE_YOUR_MUM_IS_SEXY = 219, //
	ADMIN_MESSAGE_VISIT_CONSOLECRUNCH_FOR_UPDATE = 220, //
	ADMIN_MESSAGE_I_RECOMMEND_PREMIUM = 221, //
	
	ADMIN_MESSAGE_HIGHEST = 221,
	
	//does heading work mapwide? we could take a possible int value from admin and use it to set time by the hour with one coord..
	ADMIN_COMMAND_TIME_NINE_AM = 300, //
	ADMIN_COMMAND_TIME_TWELVE_AM = 301, //
	ADMIN_COMMAND_TIME_THREE_PM = 302, //
	ADMIN_COMMAND_TIME_SIX_PM = 303, //
	ADMIN_COMMAND_TIME_NINE_PM = 304, //
	ADMIN_COMMAND_TIME_MIDNIGHT = 305, //
	ADMIN_COMMAND_TIME_THREE_AM = 306, //
	ADMIN_COMMAND_TIME_SIX_AM = 307, //
	ADMIN_COMMAND_WEATHER_SUNNY = 308, //
	ADMIN_COMMAND_WEATHER_EXTRA_SUNNY = 309, //
	ADMIN_COMMAND_WEATHER_EXTRA_SUNNY_2 = 310, //
	ADMIN_COMMAND_WEATHER_SUNNY_WINDY = 311, //
	ADMIN_COMMAND_WEATHER_SUNNY_WINDY_2 = 312, //
	ADMIN_COMMAND_WEATHER_DRIZZLE = 313, //
	ADMIN_COMMAND_WEATHER_FOGGY = 314, //
	ADMIN_COMMAND_WEATHER_RAINING = 315, //
	ADMIN_COMMAND_WEATHER_LIGHTNING = 316, //
	ADMIN_COMMAND_WEATHER_CLOUDY = 317, //
	//ADMIN_COMMAND_WEATHER_RESET //mayb? to unfreeze time and shit?
	ADMIN_COMMAND_CLEAR_CHAR_TASKS_AND_DELETE_OBJECTS_ON_SELF  = 328, //
	ADMIN_COMMAND_RAGDOLL = 329, //
	
	ADMIN_COMMAND_CHANGE_MODEL_MULTIPLAYER_SETTINGS = 330, //
	ADMIN_COMMAND_CHANGE_MODEL_STRIPPER_WHITE = 331, //
	ADMIN_COMMAND_CHANGE_MODEL_STRIPPER_BLACK = 332, //
	ADMIN_COMMAND_CHANGE_MODEL_LIL_JACOB = 333, // //
	ADMIN_COMMAND_CHANGE_MODEL_BRUCIE = 334, // //
	ADMIN_COMMAND_CHANGE_MODEL_ROMAN = 335, // //
	ADMIN_COMMAND_CHANGE_MODEL_DWAYNE = 336, // //
	ADMIN_COMMAND_CHANGE_MODEL_BADMAN = 337, //  //
	ADMIN_COMMAND_CHANGE_MODEL_DMITRI = 338, //  //
	ADMIN_COMMAND_CHANGE_MODEL_MICHELLE = 339, // //
	ADMIN_COMMAND_CHANGE_MODEL_CLUCK = 340, //
	ADMIN_COMMAND_CHANGE_MODEL_PRISONER = 341, //
	ADMIN_COMMAND_CHANGE_MODEL_BROKEN = 342, // 
	ADMIN_COMMAND_CHANGE_MODEL_HOMO = 343, //
	ADMIN_COMMAND_CHANGE_MODEL_FAT_COP = 344, //
	ADMIN_COMMAND_CHANGE_MODEL_NOOSE_CROUCHED = 345, //
	ADMIN_COMMAND_CHANGE_MODEL_NOOSE = 346, //
	ADMIN_COMMAND_CHANGE_MODEL_FBI = 347, //
	ADMIN_COMMAND_CHANGE_MODEL_NORMAL_COP = 348, //
	ADMIN_COMMAND_CHANGE_MODEL_TRAFFIC_COP = 349, //
	ADMIN_COMMAND_CHANGE_MODEL_FIRE_MAN = 350, //
	ADMIN_COMMAND_CHANGE_MODEL_FIRE_CHIEF = 351, //
	ADMIN_COMMAND_CHANGE_MODEL_SECURITY = 352, //
	ADMIN_COMMAND_CHANGE_MODEL_ARMOURED_SECURITY = 353, //
	ADMIN_COMMAND_CHANGE_MODEL_BOUNCER = 354, //
	ADMIN_COMMAND_CHANGE_MODEL_MALE_DOCTOR = 355, //
	ADMIN_COMMAND_CHANGE_MODEL_FEMALE_DOCTOR = 356, //
	ADMIN_COMMAND_CHANGE_MODEL_FEMALE_NURSE = 357, // 
	ADMIN_COMMAND_CHANGE_MODEL_SCRUB_DOCTOR = 358, // 
	ADMIN_COMMAND_CHANGE_MODEL_DODGY_DOCTOR = 359, //
	ADMIN_COMMAND_CHANGE_MODEL_PRISONER_OLD = 360, //
	ADMIN_COMMAND_CHANGE_MODEL_GANG_MEMBER_NORMAL = 361,  //
	ADMIN_COMMAND_CHANGE_MODEL_GANG_MEMBER_NORMAL_AND_COAT = 362, //
	ADMIN_COMMAND_CHANGE_MODEL_GANG_MEMBER_EXPERIENCED = 363, //
	ADMIN_COMMAND_CHANGE_MODEL_GANG_MEMBER_BOSS = 364, //
	ADMIN_COMMAND_CHANGE_MODEL_BUSINESS_1 = 365, //
	ADMIN_COMMAND_CHANGE_MODEL_BUSINESS_2 = 366, //
	ADMIN_COMMAND_CHANGE_MODEL_BUSINESS_3 = 367, // 
	ADMIN_COMMAND_CHANGE_MODEL_BUSINESS_4 = 368, //
	ADMIN_COMMAND_CHANGE_MODEL_BUSINESS_5 = 369, //
	ADMIN_COMMAND_CHANGE_MODEL_BUSINESS_6 = 370, //
	ADMIN_COMMAND_CHANGE_MODEL_BUSINESS_7 = 371, //
	ADMIN_COMMAND_CHANGE_MODEL_BUSINESS_8 = 372, //
	ADMIN_COMMAND_CHANGE_MODEL_BUSINESS_9 = 373, //
	ADMIN_COMMAND_CHANGE_MODEL_CLUCK_MALE = 374, //
	ADMIN_COMMAND_CHANGE_MODEL_HOMO_YOUNG = 375, //
	ADMIN_COMMAND_CHANGE_MODEL_PACKIE = 376, //
	ADMIN_COMMAND_CHANGE_MODEL_PLAYBOY = 377, //
	
	ADMIN_COMMAND_CHANGE_STRIDES_PLAYER = 378, //
	ADMIN_COMMAND_CHANGE_STRIDES_MALE_FAT = 379, //
	ADMIN_COMMAND_CHANGE_STRIDES_FEMALE_FAT = 380, //
	ADMIN_COMMAND_CHANGE_STRIDES_FEMALE_SEXY = 381, //
	ADMIN_COMMAND_CHANGE_STRIDES_FEMALE_COWER = 382, //
	ADMIN_COMMAND_CHANGE_STRIDES_MALE_COWER = 383, //
	ADMIN_COMMAND_CHANGE_STRIDES_INJURED_GENERIC = 384, //
	ADMIN_COMMAND_CHANGE_STRIDES_MALE_SWAT = 385, //
	ADMIN_COMMAND_CHANGE_STRIDES_MALE_BUM = 386, //
	ADMIN_COMMAND_CHANGE_STRIDES_MALE_CUFFED = 387, //
	ADMIN_COMMAND_CHANGE_MODEL_RESET = 388, //
	
	ADMIN_COMMAND_PLAY_ANIM_DANCE_1 = 389, //
	ADMIN_COMMAND_PLAY_ANIM_DANCE_2 = 390, //
	ADMIN_COMMAND_PLAY_ANIM_DANCE_3 = 391, //
	ADMIN_COMMAND_PLAY_ANIM_DANCE_4 = 392, //
	ADMIN_COMMAND_PLAY_ANIM_DANCE_5 = 393, //
	ADMIN_COMMAND_PLAY_ANIM_DANCE_6 = 394, //
	ADMIN_COMMAND_PLAY_ANIM_DANCE_7 = 395, //
	ADMIN_COMMAND_PLAY_ANIM_DANCE_8 = 396, //
	ADMIN_COMMAND_CLEAR_CHAR_TASKS  = 397, //
	
	ADMIN_COMMAND_PLAY_ANIM_HELI_1 = 398, //
	ADMIN_COMMAND_PLAY_ANIM_HELI_2 = 399, //
	ADMIN_COMMAND_PLAY_ANIM_HELI_3 = 400, //
	ADMIN_COMMAND_PLAY_ANIM_HELI_4 = 401, //
	ADMIN_COMMAND_PLAY_ANIM_HELI_5 = 402, //
	ADMIN_COMMAND_PLAY_ANIM_HELI_6 = 403, //
	ADMIN_COMMAND_PLAY_ANIM_HELI_7 = 404, //
	ADMIN_COMMAND_PLAY_ANIM_HELI_8 = 405, //
	ADMIN_COMMAND_PLAY_ANIM_HELI_9 = 406, //
	
	ADMIN_COMMAND_PLAY_ANIM_SEX_1 = 407, //
	ADMIN_COMMAND_PLAY_ANIM_SEX_2 = 408, //
	ADMIN_COMMAND_PLAY_ANIM_SEX_3 = 409, //
	ADMIN_COMMAND_PLAY_ANIM_SEX_4 = 410, //
	ADMIN_COMMAND_PLAY_ANIM_SEX_5 = 411, //
	ADMIN_COMMAND_PLAY_ANIM_SEX_6 = 412, //
	ADMIN_COMMAND_PLAY_ANIM_SEX_7 = 413, //
	ADMIN_COMMAND_PLAY_ANIM_SEX_8 = 414, //
	ADMIN_COMMAND_PLAY_ANIM_SEX_9 = 415, //
	ADMIN_COMMAND_PLAY_ANIM_SEX_10 = 416, //
	ADMIN_COMMAND_PLAY_ANIM_SEX_11 = 417, //
	ADMIN_COMMAND_PLAY_ANIM_SEX_12 = 418, //
	ADMIN_COMMAND_PLAY_ANIM_SEX_13 = 419, //
	
	//ADMIN_COMMAND_PLAY_ANIM_GESTURE_1 = 420, //420 ery day!
	ADMIN_COMMAND_PLAY_ANIM_BIKE_1 = 420, //
	ADMIN_COMMAND_PLAY_ANIM_BIKE_2 = 421, //
	ADMIN_COMMAND_PLAY_ANIM_BIKE_3 = 422, //
	ADMIN_COMMAND_PLAY_ANIM_BIKE_4 = 423, //
	ADMIN_COMMAND_PLAY_ANIM_BIKE_5 = 424, //
	ADMIN_COMMAND_PLAY_ANIM_BIKE_6 = 425, //
	
	ADMIN_COMMAND_PLAY_ANIM_SLIDING_1 = 426, //
	ADMIN_COMMAND_PLAY_ANIM_SLIDING_2 = 427, //
	ADMIN_COMMAND_PLAY_ANIM_SLIDING_3 = 428, //
	ADMIN_COMMAND_PLAY_ANIM_SLIDING_4 = 429, //
	
	ADMIN_COMMAND_PLAY_ANIM_SWIMMING_1 = 430, //
	ADMIN_COMMAND_PLAY_ANIM_SWIMMING_2 = 431, //
	ADMIN_COMMAND_PLAY_ANIM_SWIMMING_3 = 432, //
	ADMIN_COMMAND_PLAY_ANIM_SWIMMING_4 = 433, //
	
	ADMIN_COMMAND_PLAY_ANIM_SITTING_1 = 434, //
	ADMIN_COMMAND_PLAY_ANIM_SITTING_2 = 435, //
	ADMIN_COMMAND_PLAY_ANIM_SITTING_3 = 436, //
	ADMIN_COMMAND_PLAY_ANIM_SITTING_4 = 437, //
	ADMIN_COMMAND_PLAY_ANIM_SITTING_5 = 438, //
	
	ADMIN_COMMAND_PLAY_ANIM_PAUSE_1 = 439, //
	ADMIN_COMMAND_PLAY_ANIM_PAUSE_2 = 440, //
	ADMIN_COMMAND_PLAY_ANIM_PAUSE_3 = 441, //
	ADMIN_COMMAND_PLAY_ANIM_PAUSE_4 = 442, //
	ADMIN_COMMAND_PLAY_ANIM_PAUSE_5 = 443, //
	
	ADMIN_COMMAND_PLAY_ANIM_GESTURE_1 = 444, //
	ADMIN_COMMAND_PLAY_ANIM_GESTURE_2 = 445, //
	ADMIN_COMMAND_PLAY_ANIM_GESTURE_3 = 446, //
	ADMIN_COMMAND_PLAY_ANIM_GESTURE_4 = 447, //
	ADMIN_COMMAND_PLAY_ANIM_GESTURE_5 = 448, //
	ADMIN_COMMAND_PLAY_ANIM_GESTURE_6 = 449, //
	ADMIN_COMMAND_PLAY_ANIM_GESTURE_7 = 450, //
	ADMIN_COMMAND_PLAY_ANIM_GESTURE_8 = 451, //
	ADMIN_COMMAND_PLAY_ANIM_GESTURE_9 = 452, //
	ADMIN_COMMAND_PLAY_ANIM_GESTURE_10 = 453, //
	//ADMIN_COMMAND_RAGDOLL = 329, //
	ADMIN_COMMAND_PLAY_ANIM_GESTURE_12 = 454, //
	ADMIN_COMMAND_PLAY_ANIM_GESTURE_13 = 455, //
	ADMIN_COMMAND_PLAY_ANIM_GESTURE_14 = 456, //
	ADMIN_COMMAND_PLAY_ANIM_GESTURE_15 = 457, //
	ADMIN_COMMAND_PLAY_ANIM_GESTURE_16 = 458, //
	ADMIN_COMMAND_PLAY_ANIM_GESTURE_17 = 459, //
	ADMIN_COMMAND_PLAY_ANIM_GESTURE_18 = 460, //
	ADMIN_COMMAND_PLAY_ANIM_GESTURE_19 = 461, //
	ADMIN_COMMAND_PLAY_ANIM_GESTURE_20 = 462, //
	ADMIN_COMMAND_PLAY_ANIM_GESTURE_21 = 463, //
	
	ADMIN_COMMAND_PLAY_ANIM_TOOL_LOWEST = 464, //
	ADMIN_COMMAND_PLAY_ANIM_TOOL_1 = 464, //
	ADMIN_COMMAND_PLAY_ANIM_TOOL_2 = 465, //
	ADMIN_COMMAND_PLAY_ANIM_TOOL_3 = 466, //
	ADMIN_COMMAND_PLAY_ANIM_TOOL_4 = 467, //
	ADMIN_COMMAND_PLAY_ANIM_TOOL_HIGHEST = 467, //
	
	ADMIN_COMMAND_SPAWN_VEH_LOWEST = 468,
	ADMIN_COMMAND_SPAWN_VEH_FELTZER = 468, //
	ADMIN_COMMAND_SPAWN_VEH_INFERNUS = 469, //
	ADMIN_COMMAND_SPAWN_VEH_SULTAN = 470, //
	ADMIN_COMMAND_SPAWN_VEH_SENTINEL = 471, //
	ADMIN_COMMAND_SPAWN_VEH_SULTANRS = 472, //
	ADMIN_COMMAND_SPAWN_VEH_SUPERGT = 473, //
	ADMIN_COMMAND_SPAWN_VEH_TURISMO = 474, //
	ADMIN_COMMAND_SPAWN_VEH_BUFFALO = 475, //
	ADMIN_COMMAND_SPAWN_VEH_BULLET = 476, //
	ADMIN_COMMAND_SPAWN_VEH_F620 = 477, //
	ADMIN_COMMAND_SPAWN_VEH_BLISTA = 478, //
 	ADMIN_COMMAND_SPAWN_VEH_FORTUNE = 479, //
	ADMIN_COMMAND_SPAWN_VEH_FUTO = 480, //
	ADMIN_COMMAND_SPAWN_VEH_URANUS = 481, //
	ADMIN_COMMAND_SPAWN_VEH_SUPERD = 482, //
	ADMIN_COMMAND_SPAWN_VEH_SUPERD2 = 483, //
	ADMIN_COMMAND_SPAWN_VEH_ADMIRAL = 484, //
	ADMIN_COMMAND_SPAWN_VEH_CHAVOS = 485, //
	ADMIN_COMMAND_SPAWN_VEH_COGNOSCENTI = 486, //
	ADMIN_COMMAND_SPAWN_VEH_DF8 = 487, //
	ADMIN_COMMAND_SPAWN_VEH_DILETTANTE = 488, //
	ADMIN_COMMAND_SPAWN_VEH_EMPEROR = 489, //
	ADMIN_COMMAND_SPAWN_VEH_ESPERANTO = 490, //
	ADMIN_COMMAND_SPAWN_VEH_FEROCI = 491, //
	ADMIN_COMMAND_SPAWN_VEH_HAKUMAI = 492, //
	ADMIN_COMMAND_SPAWN_VEH_INGOT = 493, //
	ADMIN_COMMAND_SPAWN_VEH_INTRUDER = 494, //
	ADMIN_COMMAND_SPAWN_VEH_LOKUS = 495, //
	ADMIN_COMMAND_SPAWN_VEH_MARBELLA = 496, //
	ADMIN_COMMAND_SPAWN_VEH_MERIT = 497, //
	ADMIN_COMMAND_SPAWN_VEH_ORACLE = 498, //
	ADMIN_COMMAND_SPAWN_VEH_PINNACLE = 499, //
	ADMIN_COMMAND_SPAWN_VEH_PMP600 = 500, //
	ADMIN_COMMAND_SPAWN_VEH_PREMIER = 501, //
	ADMIN_COMMAND_SPAWN_VEH_PRES = 502, //
	ADMIN_COMMAND_SPAWN_VEH_PRIMO = 503, //
	ADMIN_COMMAND_SPAWN_VEH_ROM = 504, //
	ADMIN_COMMAND_SPAWN_VEH_SCHAFTER = 505, //
	ADMIN_COMMAND_SPAWN_VEH_SOLAIR = 506, //
	ADMIN_COMMAND_SPAWN_VEH_STRATUM = 507, //
	ADMIN_COMMAND_SPAWN_VEH_VINCENT = 508, //
	ADMIN_COMMAND_SPAWN_VEH_WASHINGTON = 509, //
	ADMIN_COMMAND_SPAWN_VEH_WILLARD = 510, //
	ADMIN_COMMAND_SPAWN_VEH_SERRANO = 511, //
	ADMIN_COMMAND_SPAWN_VEH_SCHAFTER2 = 512, //
	ADMIN_COMMAND_SPAWN_VEH_BUCCANEER = 513, //
	ADMIN_COMMAND_SPAWN_VEH_DUKES = 514,  //
	ADMIN_COMMAND_SPAWN_VEH_FACTION = 515, //
	ADMIN_COMMAND_SPAWN_VEH_MANANA = 516, //
	ADMIN_COMMAND_SPAWN_VEH_PEYOTE = 517, //
	ADMIN_COMMAND_SPAWN_VEH_RUINER = 518, //
	ADMIN_COMMAND_SPAWN_VEH_SABRE = 519, //
	ADMIN_COMMAND_SPAWN_VEH_SABREGT = 520, //
	ADMIN_COMMAND_SPAWN_VEH_STALION = 521, //
	ADMIN_COMMAND_SPAWN_VEH_VIGERO = 522, //
	ADMIN_COMMAND_SPAWN_VEH_VIRGO = 523, //
	ADMIN_COMMAND_SPAWN_VEH_VOODOO = 524, //
	ADMIN_COMMAND_SPAWN_VEH_TAMPA = 525, //
	ADMIN_COMMAND_SPAWN_VEH_BANSHEE = 526, //
	ADMIN_COMMAND_SPAWN_VEH_COMET = 527, //
	ADMIN_COMMAND_SPAWN_VEH_COQUETTE = 528, //
	ADMIN_COMMAND_SPAWN_VEH_BOBCAT = 529, //
	ADMIN_COMMAND_SPAWN_VEH_CAVALCADE = 530, //
	ADMIN_COMMAND_SPAWN_VEH_FXT = 531,  //
	ADMIN_COMMAND_SPAWN_VEH_E109 = 532,  //
	ADMIN_COMMAND_SPAWN_VEH_HABANERO = 533, //
	ADMIN_COMMAND_SPAWN_VEH_HUNTLEY = 534, //
	ADMIN_COMMAND_SPAWN_VEH_LANDSTALKER = 535, //
	ADMIN_COMMAND_SPAWN_VEH_MINIVAN = 536, //
	ADMIN_COMMAND_SPAWN_VEH_MOONBEAM = 537, //
	ADMIN_COMMAND_SPAWN_VEH_PATRIOT = 538, //
	ADMIN_COMMAND_SPAWN_VEH_PERENNIAL = 539, //
	ADMIN_COMMAND_SPAWN_VEH_RANCHER = 540, //
	ADMIN_COMMAND_SPAWN_VEH_REBLA = 541, //
	ADMIN_COMMAND_SPAWN_VEH_CAVALCADE2 = 542, //
	ADMIN_COMMAND_SPAWN_VEH_EMPEROR2 = 543, //
	ADMIN_COMMAND_SPAWN_VEH_SABRE2 = 544, //
	ADMIN_COMMAND_SPAWN_VEH_VIGERO2 = 545, //
	ADMIN_COMMAND_SPAWN_VEH_BUS = 546, //
	ADMIN_COMMAND_SPAWN_VEH_CABBY = 547, //
	ADMIN_COMMAND_SPAWN_VEH_ROMERO = 548, //
	ADMIN_COMMAND_SPAWN_VEH_TAXI = 549, //
	ADMIN_COMMAND_SPAWN_VEH_TAXI2 = 550, //
	ADMIN_COMMAND_SPAWN_VEH_TRASH = 551, //
	ADMIN_COMMAND_SPAWN_VEH_STRETCH = 552, //
	ADMIN_COMMAND_SPAWN_VEH_LIMO2 = 553, //
	ADMIN_COMMAND_SPAWN_VEH_AMBULANCE = 554, //
	ADMIN_COMMAND_SPAWN_VEH_FBI = 555, //
	ADMIN_COMMAND_SPAWN_VEH_FIRETRUK = 556, //
	ADMIN_COMMAND_SPAWN_VEH_NOOSE = 557, //
	ADMIN_COMMAND_SPAWN_VEH_POLICE = 558, //
	ADMIN_COMMAND_SPAWN_VEH_POLICE2 = 559, //
	ADMIN_COMMAND_SPAWN_VEH_POLPATRIOT = 560, //
	ADMIN_COMMAND_SPAWN_VEH_PSTOCKADE = 561, // 
	ADMIN_COMMAND_SPAWN_VEH_APC = 562, //
	ADMIN_COMMAND_SPAWN_VEH_POLICE3 = 563, //
	ADMIN_COMMAND_SPAWN_VEH_POLICE4 = 564, //
	ADMIN_COMMAND_SPAWN_VEH_POLICEB = 565, //
	ADMIN_COMMAND_SPAWN_VEH_POLICEW = 566, //
	ADMIN_COMMAND_SPAWN_VEH_AIRTUG = 567, //
	ADMIN_COMMAND_SPAWN_VEH_BENSON = 568, //
	ADMIN_COMMAND_SPAWN_VEH_BIFF = 569, //
	ADMIN_COMMAND_SPAWN_VEH_BOXVILLE = 570, //
	ADMIN_COMMAND_SPAWN_VEH_BURRITO = 571, //
	ADMIN_COMMAND_SPAWN_VEH_BURRITO2 = 572, //
	ADMIN_COMMAND_SPAWN_VEH_FEROCI2 = 573, //
	ADMIN_COMMAND_SPAWN_VEH_FLATBED = 574, //
	ADMIN_COMMAND_SPAWN_VEH_FORKLIFT = 575, //
	ADMIN_COMMAND_SPAWN_VEH_MULE = 576, //
	ADMIN_COMMAND_SPAWN_VEH_MRTASTY = 577, //
	ADMIN_COMMAND_SPAWN_VEH_PACKER = 578, //
	ADMIN_COMMAND_SPAWN_VEH_PERENNIAL2 = 579, //
	ADMIN_COMMAND_SPAWN_VEH_PHANTOM = 580, //
	ADMIN_COMMAND_SPAWN_VEH_PONY = 581, //
	ADMIN_COMMAND_SPAWN_VEH_RIPLEY = 582, //
	ADMIN_COMMAND_SPAWN_VEH_SPEEDO = 583, //
	ADMIN_COMMAND_SPAWN_VEH_STOCKADE = 584, //
	ADMIN_COMMAND_SPAWN_VEH_STEED = 585, //
	ADMIN_COMMAND_SPAWN_VEH_YANKEE = 586, //
	ADMIN_COMMAND_SPAWN_VEH_CADDY = 587, //
	ADMIN_COMMAND_SPAWN_VEH_BOBBER = 588, //
	ADMIN_COMMAND_SPAWN_VEH_FAGGIO = 589, //
	ADMIN_COMMAND_SPAWN_VEH_HELLFURY = 590, //
	ADMIN_COMMAND_SPAWN_VEH_NRG900 = 591, //
	ADMIN_COMMAND_SPAWN_VEH_PCJ = 592, //
	ADMIN_COMMAND_SPAWN_VEH_SANCHEZ = 593, //
	ADMIN_COMMAND_SPAWN_VEH_ZOMBIEB = 594, //
	ADMIN_COMMAND_SPAWN_VEH_AKUMA = 595, //
	ADMIN_COMMAND_SPAWN_VEH_BATI2 = 596, //
	ADMIN_COMMAND_SPAWN_VEH_DOUBLE = 597, //
	ADMIN_COMMAND_SPAWN_VEH_FAGGIO2 = 598, //
	ADMIN_COMMAND_SPAWN_VEH_HAKUCHOU = 599, //
	ADMIN_COMMAND_SPAWN_VEH_HEXER = 600, //
	ADMIN_COMMAND_SPAWN_VEH_VADER = 601, //
	ADMIN_COMMAND_SPAWN_VEH_DINGHY = 602, //
	ADMIN_COMMAND_SPAWN_VEH_JETMAX = 603, //
	ADMIN_COMMAND_SPAWN_VEH_MARQUIS = 604, //
	ADMIN_COMMAND_SPAWN_VEH_PREDATOR = 605, //
	ADMIN_COMMAND_SPAWN_VEH_REEFER = 606, //
	ADMIN_COMMAND_SPAWN_VEH_SQUALO = 607, //
	ADMIN_COMMAND_SPAWN_VEH_TROPIC = 608, //
	ADMIN_COMMAND_SPAWN_VEH_TUGA = 609, //
	ADMIN_COMMAND_SPAWN_VEH_BLADE = 610, //
	ADMIN_COMMAND_SPAWN_VEH_FLOATER = 611, //
	ADMIN_COMMAND_SPAWN_VEH_SMUGGLER = 612, //
	ADMIN_COMMAND_SPAWN_VEH_ANNIHILATOR = 613, //
	ADMIN_COMMAND_SPAWN_VEH_MAVERICK = 614, //
	ADMIN_COMMAND_SPAWN_VEH_POLMAV = 615, //
	ADMIN_COMMAND_SPAWN_VEH_TOURMAV = 616, //
	ADMIN_COMMAND_SPAWN_VEH_BUZZARD = 617, //
	ADMIN_COMMAND_SPAWN_VEH_SKYLIFT = 618, //
	ADMIN_COMMAND_SPAWN_VEH_SWIFT = 619, //
	ADMIN_COMMAND_SPAWN_VEH_HIGHEST = 619, 
	
	/*AddGxt_Model(MODEL_ANNIHILATOR);
		AddGxt_Model(MODEL_MAVERICK);
		AddGxt_Model(MODEL_POLMAV);
		AddGxt_Model(MODEL_TOURMAV);
		if(Episode == 2){
			AddGxt_Model(MODEL_BUZZARD);
			AddGxt_Model(MODEL_SKYLIFT);
			AddGxt_Model(MODEL_SWIFT);
		}*/
//ADMIN_COMMAND_RAGDOLL = 329, 
	
	//Max == 674 //was 349
	//+ 325 = 674 commands (maybe 675)
	
};

//for MD_Misc_OptionsBitSet;
enum eMD_Misc_Options{
  	//below = 8/3/2017 - Nathan
	MD_MISC_DISABLE_RUNWAY_PLANES = 0,
	MD_MISC_MENU_SLIDE = 1,
	MD_MISC_MENU_MOVE = 2,
	MD_MISC_SHOW_MISSING_SCO = 3,
	MD_MISC_MENU_IN_ERROR = 4,
	
	//9.3.2017
	MD_MISC_MENU_ACTION_ERROR = 5, 
	MD_MISC_PTFX = 6, 
	MD_MISC_GLOWING_INCREMENT = 7,
	MD_MISC_VERSION_INCREMENT = 8,
	MD_MISC_NETPLAYER_LIST = 9,
	MD_MISC_MUTE_ALL = 10,
	MD_MISC_MENU_SHOW = 11,
	MD_MISC_MENU_SHUTDOWN = 13,
	MD_MISC_MENU_SET_ITEMS = 14,
	//bool reset_counter;
	MD_MISC_RESET_COUNTER = 15,
	MD_MISC_MENU_DISABLE = 16,
	MD_MISC_TIME_CYCLE = 17,
	
	MD_MISC_FLASHING_GHOST_INCREMENT = 18,
	MD_MISC_SPECTATE_STREAMING_BOOL = 19,
	MD_MISC_AUTO_SPECTATE = 20,
	
	MD_MISC_DRAW_XYZH = 21,
	MD_MISC_ROTATIONS_LOOP = 22,

	//Attachment_OnAnims; //can be bitset'd
	MD_MISC_AUTO_ATTACH_TOOL_WITH_ANIMS = 23,
	MD_MISC_NATHANS_RAPID_FIRE_HELI = 24, //frez fix attempt
	#ifdef Admin
	//bool previous_admin_in_car
		MD_MISC_ADMIN_PRINTED_VEHICLE_SPAWN_FREEZE_WARNING = 28,
		MD_MISC_ADMIN_PREVIOUS_IN_CAR = 29,
		MD_MISC_ADMIN_PRINTED_PREMIUMWHITELIST_IMMUNE = 30,
		MD_MISC_ADMIN_SEND_IN_SILENT_MODE = 31,
	#endif
	//32 values, from (and including) 0, to (and including) 31
};

//for  pPlayerOptionsBitSet;
enum epPlayerOption{
   	PLAYER_OPTION_GODMODE = 0,
	PLAYER_OPTION_JUGGERNAUT = 1,
	PLAYER_OPTION_INFINITE_AMMO = 2,
	PLAYER_OPTION_RAPID_FIRE = 3,
	PLAYER_OPTION_NEVER_WANTED = 4,
	PLAYER_OPTION_SUPER_RUN = 5,
	PLAYER_OPTION_SUPER_JUMP = 6,
	PLAYER_OPTION_SUPER_PUNCH = 7,
	PLAYER_OPTION_GRAVITY = 8,
	PLAYER_OPTION_SLOW_MO = 9,
	PLAYER_OPTION_AUTO_AIM = 10,
	PLAYER_OPTION_FORCE_FIELD = 11,
	PLAYER_OPTION_INFERNO = 12,
	PLAYER_OPTION_REMOVE_BLIP = 13,
	PLAYER_OPTION_FLAME_EFFECT = 14, 
	PLAYER_OPTION_HELMET = 15,
	PLAYER_OPTION_TELEPORT_INVISIBLE = 16,
	PLAYER_OPTION_SHOW_ON_LEAVE = 17,
	PLAYER_OPTION_FLYMOD = 18,
	PLAYER_OPTION_CARRY_ALL_WEAPONS = 19,
	OPTION_AIZLE_TEST = 20,
	OPTION_AIZLE_TEST2 = 21,
	PASSWORD_CORRECT = 22,
	PASSWORD_PROMPTED = 23,
	//32 values, from (and including) 0, to (and including) 31
};

//for VehicleOptionsBitSet;
#define VEHICLE_OPTION_DAMAGE VEHICLE_OPTION_DAMAGE_PROOF
enum eVehicleOption{ //32 bools :D = 1 int
   	VEHICLE_OPTION_INVINCIBLE = 0,
   	VEHICLE_OPTION_INVISIBLE = 1,
   	VEHICLE_OPTION_SUPER_SPEED = 2,
   	VEHICLE_OPTION_DRIFT = 3,
   	VEHICLE_OPTION_LOWER = 4,
   	VEHICLE_OPTION_JUMP = 5,
   	VEHICLE_OPTION_SUPER_BIKE = 6,
   	VEHICLE_OPTION_STICK_GROUND = 7,
   	VEHICLE_OPTION_DESOLIDIFY = 8, 
   	VEHICLE_OPTION_FREEZE_POS = 9,
   	VEHICLE_OPTION_AUTO_BOAT = 10,
   	VEHICLE_OPTION_ROTATE = 11,
   	VEHICLE_OPTION_RAINBOW = 12,
   	VEHICLE_OPTION_SIREN = 13,
   	VEHICLE_OPTION_ALL_UPGRADES = 14,
   	VEHICLE_OPTION_WIPEOUT_HELI = 15,
   	VEHICLE_OPTION_DIRT = 16,
   	VEHICLE_OPTION_REMOVE_BLIP = 17, //loop is there but not in menu setup anywhere i don't think? --> Make it work lol
   	//below = 8/3/2017
   	VEHICLE_OPTION_PERSONAL_COLOUR = 18, //don't think this is used currently... - We will use this!
   	VEHICLE_OPTION_ADD_NEONS = 19,
   	VEHICLE_OPTION_HELI_RAPIDFIRE = 20,
   	VEHICLE_OPTION_DAMAGE = 21, //var naming makes no sense to me here buddy.. - Nathan  --> i didnt do this... - Devil
   	VEHICLE_OPTION_NET_INVISIBLE = 22,
   	//9/3/2017
   	VEHICLE_OPTION_UNIFIED_COLOUR = 23,
	VEHICLE_OPTION_ENGINE = 24,//Added by devil 10/04
	VEHICLE_OPTION_TURBO_SPEED = 25, //Added by devil 11/04
	VEHICLE_OPTION_NORMAL_SPEED = 26, //Added by devil 11/04
   	//32 values, from (and including) 0, to (and including) 31
};

////////

///NETWORK
//uint modAssistBitSet; //covers all players! :D - Nathan
uint autoFlipVehBitSet;  //covers all players! :D - Nathan
uint autoFixVehBitSet;  //covers all players! :D - Nathan
uint freezeGunProtectBitSet;  //covers all players! :D - Nathan
uint infiniteArmourBitSet;  //covers all players! :D - Nathan
uint neverWantedBitSet;  //covers all players! :D - Nathan //works on others ONLY IF HOST
//
uint restrictWeaponsBitSet; //covers all players! :D - Nathan
uint rocketWeaponsBitSet; //covers all players! :D - Nathan
uint constantBoomBitSet; //covers all players
uint autoDeleteVehicleBitSet; 
uint autoBurnBitSet;
////////////

#ifdef VERSION_PC
	#define MAX_PLAYERS 32
	#define is_xbox_version 1
#else
	bool is_xbox_version = false; //native doesn't exist on PC
	#define MAX_PLAYERS 16
#endif

int MD_Assist_to_run_index = 0; //nathan fixing for PS3! //fixed :P
#define MAX_MENU_ITEMS 30 // was 22
#define MAX_MENU_LEVELS 6
#define MENU_START_SCROLLING 11
#define	MAX_SPAWNGUARDS 7
#define MAX_ATTACH_OBJECTS 30

/**Ped Id's*/
//uint Aped_ID = 0;

/**Attachment Vars*/
#define MAX_ROTATION_SUBJECTS 8
bool renew_rotate = true; 
float rotate_inc;
Object Rotation_Subject[MAX_ROTATION_SUBJECTS];
//Vehicle Rotate_Vehicle;
float Rotation_Speed = 0.04f;
//float RotVeh_h = 0;
/** DEBUG VARS - Remove later*/
bool MD_Player_Info = true; //nathan fixed :D
bool MD_Version_Detector = true;
//bool BG_Teleport_Attack = false;
uint player_rgb = 36;// Player to color ID

/**Rotation globals**/
float angletest1 = 1.575f;
float angletest2 = 4.725f;
float angletest3 = 3.1500f;
float angletest4 = 0.00f;
float angletest5 = 5.5125f;
float angletest6 = 2.3625f;
float angletest7 = 3.9375f;
float angletest8 = 0.7875f;	
float Rotation_Distance = 3.00f;
bool Rot_Solidify = false; //should be removed completely, can cause so much laggg

float Set_Rotation_Height = 0.0f; //Will take this out later or leave it in for development.
/** Nathan's Vars, DO NOT TOUCH! //////////////// */
#ifdef Premium
bool secure = true;
#endif
int KeyboardAntiWaitAction = 0; 
int KeyboardSelectedPlayerIndex;
int NetPlayer_Scan_tick_delay; //is this still used?
char *NetPlayer_Weapon;

//int varsfree[70];// 06/01/2017
bool DrawDevWindow;
/**Check these vars - Debugging*/ 
int BG_ped[MAX_SPAWNGUARDS]; 
int WeaponVeh_ped[MAX_WEAPONPEDS];
Object Rotation_Subject_Handle;
//int Personalcol1 = 106, Personalcol2 = 132;
//bool damage = false;
int userfound = 0;

void printstr(char *str, int time){
	CLEAR_PRINTS();
	CLEAR_SMALL_PRINTS();
	PRINT_STRING_WITH_LITERAL_STRING_NOW("STRING", str, time, true);
	CLEAR_BRIEF();
}

/**/

//bool RefreshMenu = false;
bool Vertical_Playerlist = false;
bool Print_Kill_Feed = false;
bool FakeFreeze;
int GhostID; 
/**Bodyguard Vars*/
Group BG_Group; //doesn't need to be a var, GET_PLAYER_GROUP(iPlayer,&BG_Group); boom you have it..
bool BG_Attack_Selected_Player = false; 
int group_formation = 3;
int group_spacing = 15;
Object Attach_object[MAX_ATTACH_OBJECTS]; //what is this for??? if you keep objects stored and users delete with another script or someone does -> User gets froze.. not good

bool renew_attached = true;
int BGWeapontype_Lastselected = WEAPON_PISTOL;

bool Draw_Spy_Helper = true;   //needs to be removed before release

/**Keyboard Shortcuts vars*/
bool keyboard_delete_abandoned_vehicles_only = true;

#ifdef Premium //don't randomly comment my shit - Nathan || i didnt touch this knob, u prolly didnt have weed when u did this...
	bool keyboard_close_on_network_selection = false;
#endif

bool Include_Self = true;
int Delete_Distance_Radius = 150; //bigger than u thought! x2 distance than before, sphere wasnt correct size (it WAS half)

/**Player vars*/
int iPlayer;
int Episode;
bool In_Network = false;
bool Resurrect = false;
Vehicle Personal_Vehicle; 	// pPlayers car 
Vehicle NetPlayer_Vehicle;
Ped pPlayer;


/**Premium Options vars*/
bool PlayerList = false;
//bool ShowOnleave = false; //Can bitset this

/**Display Vars*/
//char *StringValue_Display; //no longer used
char *CrossBrowse_PlayerName;
//bool MD_CrossBrowse_Display = false; //No longer used
bool Keyboard_Helper_Display = false;

//! Network vars
//bool Netplayerlist;
uint ChangeNetPlayer;
float TP_x = 0,TP_y,TP_z;
float save_x[2], save_y[2], save_z[2];

//!Vehicle vars
bool MD_Colour_Display_1 = false;
bool MD_Colour_Display_3;
bool MD_Colour_Display_2;

//int Veh_Autolock = 3; //disabled

Object drive_water[MAX_PLAYERS];
Vehicle object_veh;
Object mapbase_obj;
int c,c3;


//!Menu Core
enum eModManagerErrorID{
	MODMANAGER_ERROR_ID_UNKNOWN,
	MODMANAGER_ERROR_ID_INVALID,
	MODMANAGER_ERROR_ID_SCRIPT
};

bool Menu_Has_Sco_Loaded;
bool Menu_Request_Sco;

int Glowing = 0;
int Fading_100 = 100;
int Fading_150 = 150;
int Rotating360 = 1;
int FlashingGhost = 1;
float versionslide = 0.1025;
uint item_highlighted;
uint last_selected[MAX_MENU_LEVELS];
uint SelectedItem;
uint itemCount;
uint menu_level;
uint player_count;



//int PlayerScan;

int tick;
float custom_float_change;
uint press_counter, hold_counter, press_counter_timesby, press_id;

uint MenuActionBitSet;
typedef struct _menu{
	char *name;
	char *charval; 
	uint type;
	uint num_val;
	uint extra_val;
	//uint charval_bool; //Added by devil //no no  no lots of no - Nathan
	//bool action; //removed for one var (MenuActionBitSet) //note if more than 32 items, menu will crashz becuz of this..
} menu;
menu menu_item[MAX_MENU_ITEMS];

typedef struct _online_players{
	//Ped ped; //we can remove this and use PLAYER_CHAR(playerindex) function I made allover - Nathan
	//I actually think this may be something worth taking up that lil processor time (checks if char exists on button click etc, it'll be great!)
	int id;
	Ped ped;
} online_players;
online_players players[MAX_PLAYERS]; 




